# Generated by Django 3.1 on 2020-09-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200211_1303'),
        ('products', '0002_auto_20200829_1048'),
    ]

    operations = [
    ]
